# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20161026_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profs',
            name='ble',
        ),
        migrations.AddField(
            model_name='profs',
            name='room',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profs',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Available Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profs',
            name='motion_sensor',
            field=models.CharField(default='OFF', max_length=10),
        ),
    ]
