# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20161107_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profs',
            name='time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
